### ISSUE TITLE
Mono version issues under Linux

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#2078]
The version compiled with Mono 3.2.3 crash at startup for me on Windows.

Mono version critical problems:
- [ ] Interactive rebase doesn't work
- [ ] Create Branch: At the window opening, the focus is not set on the branch name input field
- [ ] Diff panel lines not erased when switching to a different commit #3008
- [ ] Diff view toolbar incorrect layout [image](https://cloud.githubusercontent.com/assets/224272/19401541/8c79172c-9264-11e6-9e70-1486bbac6079.png)
- [ ] Revision row partially shows wrapped text #3087
- [ ] Create branch dialog incorrect layout
  [image](https://cloud.githubusercontent.com/assets/224272/19401625/ff2cc4e4-9264-11e6-87e1-0cad59883ea5.png)
- [ ] Submodules form show wrong names [image](https://cloud.githubusercontent.com/assets/224272/19401553/9f7ec20e-9264-11e6-88ea-102ce33da15a.png)
- [ ] Autoupdate download msi installer, should zip file
- [ ] Repository graph not showed after several lines [image](https://cloud.githubusercontent.com/assets/224272/19401796/fe3aa7ee-9265-11e6-9df7-289e4734881d.png)
- [ ] Cannot enter HTTP password #1758
- [ ] Putty doesn't work on Linux. Remove it?
- [ ] Cannot run TranslationApp.exe (should run mono TranslationApp.exe)
- [ ] Settings window layout #3380
- [x] Stash window layout [image](https://cloud.githubusercontent.com/assets/224272/19400839/c0343960-9260-11e6-9330-ff7d1a031248.png)
- [x] Checkout branch form size
- [x] Dashboard doesn't show repositories, common actions and links #1713 
- [x] Form contributors doesn't wrap lines
- [x] Cancel in open repository not work
- [x] Impact plugin doesn't show anything
- [x] Statistic plugin crash
- [x] FormStatus show on OK
- [x] Font too large for all forms
- [x] SVN Fetch/Rebase/DCommit
- [x] Resize commit window not resize text box
- [x] GDIPlus.CheckStatus crash #1213
  Update: latest check with Mono 4.6.1

**Comment by feinstaub** [comment]
@fraga @KindDragon @spdr870 I added a wiki page for Linux: https://github.com/gitextensions/gitextensions/wiki/Git-Extensions-on-Linux. There I put links to an openSUSE build service package which I made.

**Comment by KindDragon** [comment]
@feinstaub Nice. Thank you

**Comment by tonyeung** [comment]
in order to get this working, i modified the gitext.sh from

```
#!/bin/bash
mono GitExtensions.exe "$@" &
```
to
```
#!/bin/bash
rm -rf ~/.local/share/GitExtensions && mono GitExtensions.exe "$@" &
```

**Comment by KindDragon** [comment]
Let's keep it open for 2.51

**Comment by Wirone** [comment]
Revision links are not clickable on Mono:

![image](https://user-images.githubusercontent.com/600668/54995613-6306ff80-4fc7-11e9-9a24-8dfaa2338905.png)

Regex was matched, JIRA issue was determined, but in commit summary issue link is not clickable.

GitExtensions 2.51.05, Mono JIT compiler version 5.10.1.20

**Comment by RussKie** [comment]
@Wirone please raise a new issue

**Comment by Wirone** [comment]
@RussKie created #6407

**Comment by GintasS** [comment]
Abandoning this because of age. Also, I can see that a new issue was raised too. I think we should close this.
