### ISSUE TITLE
BrowseDiff should show differences to all selected revisions

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4564]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The diff tab shows differences to the selected (last clicked) revision from parent (if one selected) or first select (if two). With more than two selected the message was set to "Operation not supported".
For merge commits, all parents are shown though.

**What is the expected behavior?**
Show the differences for all selected versions also for multiple selected versions.
#4562 builds the support for this, a few issues like #4387 and #4396 remains.

Requires #4562 and #4563

Will submit several PRs from this:
- [x] #4565 Browse Diff: Incorrect comparision for multiple parents 
- #4566 Allow compare to several revisions (part of #4569, for review only)
- [x] #4567 minor cleanups
- [x] #4568 Submodule multi selection
- [ ] #4569  A combined PR with #4387 #4396 visual update and tests

**Comment by gerhardol** [comment]
Will submit several PRs from this (preliminary):
 [ ] Arguments to OpenDiffTool
 [ ] Allow compare to several revisions
 [ ] minor cleanups

**Comment by RussKie** [comment]
@gerhardol  I've unchecked the points for unmerged PRs
Once they are merged - we can tick them off, makes it easier to track the progress

**Comment by gerhardol** [comment]
> I presume the order in which you've listed them - is the order in which we want to get them in, right?

Yes
I have set dependencies so #4569 depends on #4566 that depends on #4565 
#4566 is not really dependent on #4565 but it was easier to handle #4569 then
