### ISSUE TITLE
High DPI Issues

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4775]
# High DPI Issues

Issues by form/dialog:

- [ ] Remote repositories (default behaviours tab) (#5028)
- [ ] Recent repositories settings (#4774)
- [x] ~Settings: Colors~ (PR part of #5081)
- [x] ~Settings: Confirmations~ (PR #5560)
- [x] ~Settings: Shell extension~ (PR #5561)
- [x] ~Delete tag~ (#5300, #5380, PR #5381)
- [x] ~About dialog~ (#5201, PR #5248)
- [x] ~Commit template settings form~ (#5059)
- [x] ~FormCommit: Text editor markers~ (#5024, PR #5215)
- [x] ~FormCommit: TextBox watermark~ (#5023, PR #5087)
- [x] ~GravatarControl image scaling~ (PR #4711)
- [x] ~Settings: treeview navigation~ (#4949, PR #4950)
- [x] ~Settings: Change HOME~ (#4690, PR #4755, v2.51 #4780)
- [x] ~Remote repositories~ (PR #4714, v2.51 6d49acd2de4ae719b87c7e369a24c085dbe71ffd)
- [x] ~Revision graph / grid~ (PR #4772)
- [x] ~Open local repository~ (#4174, PR #4887, v2.51 #4893)
- [x] ~Clean working directory~ (#3828, PR #4890, v2.51 #4891)
- [x] ~Clone repository~ (#4776, PR #4888, v2.51 7dfe467752d02a8d030961ae03d65b3586ee767b)
- [x] ~Commit picker control~ (#4702 #4862, PR #4889, v2.51 268fa27d759241aac59e3045268b9fb05a31abe9)
- [x] ~NBug scaling issues~ (#4989, PR gitextensions/NBug#10)

Issues by control:

- [ ] Splitter positions
- [x] ~Tab control header is too small~ (#4777)
- [x] ~Columns aren't sized correctly~ (#3603, PR #4772)
- [x] ~Images in buttons are too small~ (#4778, PR #4772)
- [x] ~Tree view icons are too small~ (PR #4772)
- [x] ~Data grid columns are too sma~l~ (PR #4772)

Longer term goals:

- [ ] High DPI icons (#4825)
- [ ] Per-monitor DPI awareness (#4822)

---

# Reporting new issues

1. Search for [existing DPI issues](https://github.com/gitextensions/gitextensions/issues?utf8=%E2%9C%93&q=label%3A%22visual+hdpi%22+)
  - If one exists, see if you can add something useful to it, like a screenshot. Be sure to mention your scaling setting (eg: 125%). Vote on issues to increase their priority.
  - Remember that the issue may have been fixed on `master` since the version you are using was built.
Try the latest portable package build on master: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

2. If no issue exists, create a new one
  - Focus on one form/dialog (though you may point out multiple issues within)
  - Explain what feature has the issue
  - In addition to the regular template data, include:
    - your display scaling setting (e.g. 125%) as this is more useful than "4K" or "32 inch monitor"
    - your .NET framework version (4.6 introduced several DPI improvements)
  - Add as many screenshots as you can, ideally at different scaling levels

Once the issue is reviewed it will be added to this issue for tracking.

# Workarounds

GitExtensions aims to support High DPI screen settings. As such, it tells the host OS that it is "DPI aware" and can scale itself to the user's preferred resolution.

Currently GitExtensions is quite usable on high DPI screens, though some parts still look a bit odd.

If you prefer, you can override the DPI awareness setting and Windows will lie, telling GitExtensions that the display is the default 96 DPI, and not to do any scaling. In such a case, Windows will stretch the UI as necessary.

To override this setting:

1. Navigate to `%ProgramFiles(x86)%\GitExtensions\` 
2. Right-click on `GitExtensions.exe`
3. Select the _Compatibility_ tab
4. In the _Settings_ group, ensure _Override high DPI scaling behaviour" is checked
5. Select _System_ from the drop down

<img src="https://user-images.githubusercontent.com/350947/38330839-8e19ed36-3849-11e8-9922-5ffb46953dba.png" width="400" />

# .NET Framework version

.NET 4.6+ applies scaling to some controls. If you are only an older version, you may like to upgrade.

https://blogs.msdn.microsoft.com/dotnet/2015/07/20/announcing-net-framework-4-6/

# Developer Resources

- https://stackoverflow.com/q/22735174/24874

From [@RussKie](https://github.com/gitextensions/gitextensions/pull/5050#issuecomment-395911042):

> The way I fix high dpi issues is:
> - modify layouts when Windows is scaled first (e.g. 200%),
> - remember what is changed
> - switch to standard scaling (96dpi),
> - apply the same changes and test.
>
> Having 2 computers running standard and high dpi helps, as you can apply changes simultaneously and share between them.

**Comment by RussKie** [comment]
Getting close 😎
