### ISSUE TITLE
LeftPanel Branch tree view outstanding issues

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4814]
Migrating issues identified during [the review](https://github.com/gitextensions/gitextensions/pull/4499#issuecomment-372022550) here.
Relates to #4499

If some of them addressed, we just need to tick them off.

**Outstanding:**

- [x] The selected icon is typically used to represent "Settings" or "Configurations". The proposed behaviour offers a different metaphor.
To me, the proposed looks very similar to what VS offers:
![image](https://user-images.githubusercontent.com/4403806/37241533-b413b4e4-24ae-11e8-94a9-29f5a4ae6d95.png)
- [x] Toolbar buttons must provide tooltips (proposed in #6173)
![image](https://user-images.githubusercontent.com/4403806/37241514-85e1a23e-24ae-11e8-8e98-f6db1cc8dc78.png)
----

<details>
<summary>Complete items</summary>

- [x] High DPI review
- [x] ~Toggle tree branch button must have `CheckOnClick = true` to indicate when the panel is expanded~
- [x] ~Suggest to consider adding a button to the panel above the tree similar to the VS Solution Explorer~  (#6174)
![image](https://user-images.githubusercontent.com/4403806/37241437-1b128a5a-24ad-11e8-83d3-0d4de0048319.png)
- [ ] ~Context menu must not show "Expand all", when all expanded, and not "Collapse all", when all collapsed~ Not going to do, as it requires more code than added value
![image](https://user-images.githubusercontent.com/4403806/37241416-b33f820c-24ac-11e8-828b-f0aee3c5328c.png)
- [x] ~Expand/collapse items must be also available, if clicked on tree nodes. Otherwise it may impractical to scroll to collapse~ (#5012)
![image](https://user-images.githubusercontent.com/4403806/37241405-85ea45d0-24ac-11e8-912a-6c7f192b6a20.png)
- [x] ~The tree must automatically expand to the current checked out branch.~ (#5012)
![image](https://user-images.githubusercontent.com/4403806/37241570-6887c38e-24af-11e8-9f31-bb154517c2d2.png)
- [x] ~Context menu must contain common items, such as "Manage remotes"~
![image](https://user-images.githubusercontent.com/4403806/37241416-b33f820c-24ac-11e8-828b-f0aee3c5328c.png)
- [x] ~Missing space~
![image](https://user-images.githubusercontent.com/4403806/37241693-732db134-24b1-11e8-84a6-d2d2d1e62991.png)
- [x] ~Add separator after "Checkout" item~ (#5012)
![image](https://user-images.githubusercontent.com/4403806/37241686-50fba04e-24b1-11e8-9e69-09cedf3693e8.png)
- [x] ~Currently checked out branch mustn't have "Checkout" menu~  (#5012)
![image](https://user-images.githubusercontent.com/4403806/37241607-07820242-24b0-11e8-8037-74640ca5e858.png)
- [x] ~Currently checked out branch mustn't have "Delete" menu~  (#5012)
![image](https://user-images.githubusercontent.com/4403806/37241607-07820242-24b0-11e8-8037-74640ca5e858.png)  
- [x] ~Currently checked out branch mustn't have "Force Delete" menu~ (removed in #5019, #5027)
![image](https://user-images.githubusercontent.com/4403806/37241607-07820242-24b0-11e8-8037-74640ca5e858.png)
- [ ] ~Use "delete" icon used in FormRemotes (86.png)~

</details>

**Comment by drewnoakes** [comment]
- [ ] High DPI review

**Comment by zlolik** [comment]
Are you going to add Tags to LeftPanel ?

**Comment by ivangrek** [comment]
https://github.com/gitextensions/gitextensions/pull/5525#issuecomment-711443377

> Maybe... Again if you want to collapse only this node - collapse it. No need for the contextmenu.

Also for all child nodes.
In VS apply only for child nodes.

**Comment by RussKie** [comment]
> In VS apply only for child nodes.

I suppose I can buy into this argument. But VS has a global "collapse all" button, which we don't.
I'm happy to trade the context menu buttons for one toolstrip button though (which was done in https://github.com/gitextensions/gitextensions/pull/6174).

**Comment by ivangrek** [comment]
VS has a global and for child nodes.

![image](https://user-images.githubusercontent.com/3169265/96390503-ad5d5c00-11bd-11eb-952b-26928d600e0c.png)

I don't quite understand what you are suggesting.

**Comment by RussKie** [comment]
> I don't quite understand what you are suggesting

...that we can _probably_ remove the two context menus - "Collapse all" and "Expand all".

But this will have an impact on "sort" context menu logic, so this won't likely be a simple change. So for me this a low priority work.

**Comment by bspkrs** [comment]
I do apologize if this has been asked before, but is there any way that the entire left panel can be made to be optionally displayed? Like a new toggle in the View menu. I personally never have ever used it, and now that its surface area is forced to be larger than before (some recent update made the panel have a minimum size enforced, either directly or otherwise), I would finally like to be able to just toggle it off.

If I need to open a new ticket to have this addressed, please let me know. Otherwise, I would assume that this could be added as a task for this existing ticket to reduce ticket management.

![image](https://user-images.githubusercontent.com/1561582/124929362-6ecb3400-dfce-11eb-8e90-2ee1f87d0bb2.png)

**Comment by bspkrs** [comment]
> @bspkrs you mean the 2nd button in the toolbar (next to the refresh one)?

I literally found it right as you were replying. I can't believe I've been this blind this long about a feature that always annoyed me (personally). Thanks for the reply either way!
