### ISSUE TITLE
Reduce Git commands

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#9229]
## Feature description

A number of Git commands can be combined or made more efficient to reduce execution time.
Some commands are remarkably slowed down by virus programs like Symantec, `git status` can be at least seven times slower.

A command like `git for-each-ref` can take about 300 ms with virus programs in repos at work, while the same command at home with  a faster PC and GE repo requires 30 (but occasionally 120 ms) at home.
Also `git for-each-ref` requires about the same time regardless of the filter in the Git command so a command combining fetching branches/remotes/tags at the same time and filter in code is almost three times faster than three separate Git calls.

This is currently a brief list of what I recall right now, I suggest the list is improved (add comments if you are not a member of the project and can edit the list).

### Loading

Affects the time to load or refresh a repo

* [x] #9246 `git --version` is called twice in the startup (to check version and to check existence)
* [x] `git for-each-ref` is called three times to load the sidepanel, one is enough
* [x] #9317 `git log` uses a GUID to separate branch from further data. A double \0\0 is probably enough, but the separation of commits uses null termination right now. (there were discussions in the PR where 1DEA7CC4-FB39-450A-8DDF-762FCEA28B05 was introduced). 
* [x] #9243 `git log` uses Git to separate and encode the the header and body, but still have special handling for the handling. There was also an issue some years ago that stated that the Git handling was incompatible with the GE internal handling. It is therefore maybe better to load the raw commit message body and process that. The processing can be improved in general.

Caching can be improved (switching commits)

* [ ] `git status` could be shared for GitStatusMonitor and for RevDiff listing (and GitStatusMonitor is aware of when the cache is potentially changed).
* [ ] `git diff` for file work tree items could be cached, invalidated by GitStatusMonitor
* [ ] `git for-each-ref` is needed by many different entities and could be cached, invalidated by GitStatusMonitor.

### Background

Not directly affecting interactive commands but CPU load.

* [x] #9256 `git ls-tree` lists superproject branches in subrepos. This is configurable, if enabled this loads a large number of Git commands. (Very annoying when viewing the Git Command Log, not even cancelled, the listing goes on for a minute or so). All of these are not interesting, should be limited to a number of superproject branches (suggest a setting that only can be read right now, so the value can be adjusted in the settings file if there is a need to tweak it).
* [ ] If there are submodule changes detected by Git status monitor, `git diff` for the submodule is executed. This is not always necessary, if the submodule has no submodules by themselves, this is just used to get the tool tip. The tool tip could be evaluated when the control is hovered instead, or maybe be a popup (with brief info about changes too?)
* [ ] `git rev-parse --git-common-dir` is used several times to get the module encoding to get the tooltip for changed submodules above. The status could at least be cached.

## Environment

This is primarily targeted to master, there has been a few changes compared to 3.5 already.

**Comment by RussKie** [comment]
Thank you for documenting these. I think a number of improvements we can make if we start utilising IoC/DI more, i.e. MEF. Then we can have a central git command provider, that executes commands and caches results, if appropriate.
